# Generated by Buildfy v3.0
# 2026-06-30T23:04:29.411Z
import customtkinter as ctk
import tkinter as tk

# ── Theme ──────────────────────────────────────────────
BG_MAIN = "#0F0F11"
BG_CARD = "#1A1A1F"
BG_WIDGET = "#242429"
BORDER = "#2E2E36"
TEXT = "#F2F2F3"
TEXT_MUTED = "#8B8B99"
ACCENT = "#F0525C"
ACCENT_HOVER = "#E03E48"

ctk.set_appearance_mode("dark")
ctk.set_default_color_theme("blue")


class App(ctk.CTk):
    # ── Setup ──────────────────────────────────────────────
    def __init__(self):
        super().__init__()
        self.title("My App")
        self.geometry("800x600")
        self.configure(fg_color=BG_MAIN)
        self.resizable(True, True)
        self._setup_widgets()

    # ── Widgets ────────────────────────────────────────────
    def _setup_widgets(self):
        self._Label_9bys_x = 248
        self._Label_9bys_y = 80
        self._Button_m5fr_x = 326
        self._Button_m5fr_y = 464
        self._Label_kp7d_x = 87
        self._Label_kp7d_y = 263
        self._Entry_h1e0_x = 211
        self._Entry_h1e0_y = 264

        self.Label_9bys = ctk.CTkLabel(
            self,
            text="Cadastro  de Cliente",
            text_color=TEXT,
            font=("Arial", 32),
            width=303,
            height=28,
        )
        self.Label_9bys.place(x=248, y=80)

        self.Button_m5fr = ctk.CTkButton(
            self,
            text="Cadastrar",
            fg_color="blue",
            text_color="#ffffff",
            corner_radius=8,
            hover_color=ACCENT_HOVER,
            font=("Arial", 14),
            width=120,
            height=36,
        )
        self.Button_m5fr.place(x=326, y=464)

        self.Label_kp7d = ctk.CTkLabel(
            self,
            text="Nome:",
            text_color=TEXT,
            font=("Arial", 14),
            width=120,
            height=28,
        )
        self.Label_kp7d.place(x=87, y=263)

        self.Entry_h1e0 = ctk.CTkEntry(
            self,
            placeholder_text="Nome Mauri",
            fg_color=BG_WIDGET,
            border_color=BORDER,
            text_color=TEXT,
            corner_radius=8,
            font=("Arial", 14),
            width=406,
            height=36,
            border_width=1,
            placeholder_text_color=TEXT_MUTED,
        )
        self.Entry_h1e0.place(x=211, y=264)


def main():
    app = App()
    app.mainloop()


if __name__ == "__main__":
    main()
